# Generated by Django 5.2.8 on 2025-11-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_repoanalysissession_repomessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='github_access_token',
            field=models.CharField(blank=True, help_text='Your personal GitHub access token for higher rate limits', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_search_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='searches_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gemini_api_key',
            field=models.CharField(blank=True, help_text='Your personal Gemini API key for AI features', max_length=255, null=True),
        ),
    ]
